services:
  app:
    env_file:
      - .env
    build: .
    command: bash -c "python manage.py runserver 0.0.0.0:${CONTAINER_PORT}"
    # command: bash -c "gunicorn -c config/gunicorn_config.py config.wsgi"
    volumes:
      - .:/app
    ports:
      - "127.0.0.1:${CONTAINER_PORT}:${CONTAINER_PORT}"
    restart: unless-stopped
