# Generated by Django 5.1.1 on 2024-09-14 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payback', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name': 'Settings', 'verbose_name_plural': 'Settings'},
        ),
    ]
