# Generated by Django 5.1.1 on 2024-09-14 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payback', '0002_alter_settings_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paybackuser',
            old_name='name',
            new_name='group',
        ),
        migrations.AddField(
            model_name='paybackuser',
            name='handle',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
