# Generated by Django 5.1.1 on 2024-09-14 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payback', '0003_rename_name_paybackuser_group_paybackuser_handle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paybackuser',
            name='email',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='paybackuser',
            name='group',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
