# Generated by Django 5.1.1 on 2024-09-14 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payback', '0004_alter_paybackuser_email_alter_paybackuser_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paybackuser',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
