# Generated by Django 5.1.1 on 2024-09-18 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payback', '0006_alter_questionnaire_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire', to='payback.paybackuser'),
        ),
    ]
