# Generated by Django 5.1.1 on 2024-09-23 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payback', '0008_paybackuser_user_id_short'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paybackuser',
            name='user_id_short',
        ),
    ]
