# Generated by Django 5.1.1 on 2024-09-23 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payback', '0009_remove_paybackuser_user_id_short'),
    ]

    operations = [
        migrations.AddField(
            model_name='paybackuser',
            name='initial_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
