# Generated by Django 5.1.1 on 2024-09-24 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payback', '0010_paybackuser_initial_email_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paybackuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
