# Generated by Django 5.1.1 on 2024-10-15 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payback', '0011_alter_paybackuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='paybackuser',
            name='place_in_line',
            field=models.IntegerField(default=0),
        ),
    ]
