# Generated by Django 5.1.1 on 2024-10-19 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payback', '0012_paybackuser_place_in_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='paybackuser',
            name='use_alternate_email_backend',
            field=models.BooleanField(default=False),
        ),
    ]
