# Generated by Django 5.1.1 on 2024-12-18 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payback', '0013_paybackuser_use_alternate_email_backend'),
    ]

    operations = [
        migrations.AddField(
            model_name='paybackuser',
            name='votekey',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
