# Generated by Django 5.1.1 on 2025-01-22 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payback', '0014_paybackuser_votekey'),
    ]

    operations = [
        migrations.AddField(
            model_name='paybackuser',
            name='invisible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='settings',
            name='registration_visible',
            field=models.BooleanField(default=True),
        ),
    ]
